### ISSUE TITLE
lable or label

### ISSUE THREAD

**Issue by foospidy** [cloudatcost/api#10]
For the list servers call the documentation shows one of the data attributes listed as "label", but the actual api returns that attribute as "lable". Can this be changed to "label"?

**Comment by drbraden** [comment]
I would agree, while it's easier and cheaper to do so.

**Comment by charliedrage** [comment]
We fixed this!

"lable" is still included as some applications still use this. But now you'll see "label" appear now in listservers / listtasks, etc.
