### ISSUE TITLE
Allow POST/GET for all requests

### ISSUE THREAD

**Issue by rinne** [cloudatcost/api#12]
First. Great that you are making an api! This is really appreciated.

There is really no good reason not to make methods POST-only or GET-only because they are in all practical purposes parametrised in a similar way. At least the simple ones currently available only for GET should also allow POST so that the client library would be as simple as possible.

It is arguable whether GET methods are needed at all for methods that need authentication data. For non-authenticated calls returning some static response it might be the way to go. However, since there already are GET-methods and php which the api server seems to be written in, really makes it trivial to allow both (GET and POST), GET support is easy to maintain.

**Comment by drbraden** [comment]
I think it's fine as is.  It's perfectly normal and commonly expected that read-only resources are accessed via GET, while requests that have side-effects, such as creating, updating, and deleting, are non-GET (might even be POST, PATCH, PUT, or DELETE).

Whether or not a request needs authentication is immaterial to what HTTP verb is being used.  As for allowing GET and POST for all requests, that would go against the commonly accepted best practices for API design.  It could certainly be done, but there's no real benefit in doing so.

Anyway, just my 2¢.

**Comment by rinne** [comment]
But now it seems to be pretty arbitrarily defined, which is POST and which is GET.

**Comment by charliedrage** [comment]
I would have to agree with @drbraden we try to follow as close to the POST/PUT/GET/DELETE restful API aspects. 

For listservers, listtasks, listtemplates we use GET as it's not necessarily a security concern.

For powerop and console where actual parameters modify database changes on our end it's more viable to use POST.

We've used Leanord Richardson's book (RESTful Web APIs) for reference when designing.
