### ISSUE TITLE
I would recommend not escaping forward slashes in JSON responses

### ISSUE THREAD

**Issue by drbraden** [cloudatcost/api#14]
Values coming back to us include dates and URLs that end up looking like:
* "sdate": "12\/02\/2014"
* "console": "http:\/\/panel.cloudatcost.com:52720\/console.html....

The escaping is valid JSON and parses down to the correct values, but it's unneeded escaping and causes extra work if you have to copy & paste the values somewhere that most likely does not handle the escaping correctly (ie. the "console" address into a browser address bar, you would need to manually remove the three backslashes).

**Comment by rinne** [comment]
I would recommend using default encoding, which does escape slashes. This is not strictly needed in order to be JSON compliant, but it is best practise in order to have syntax Javascript compliant and directly embeddable into HTML document.

http://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped

**Comment by charliedrage** [comment]
Hey @drbraden 

We'll be changing the date value within the console API to Unix time in the future.

In regards to the console link. One of the internal suggestions for v2 is adding another hash (alongside the currently json backslash-escaped link) of values so users can connect and parse the link themselves.

ex.

{ console => { "http":"https", "url":"panel.cloudatcost.com", "port":5720, etc. etc.

**Comment by drbraden** [comment]
@rinne , ya, I saw that SO question when I was checking if forward slashes needed escaping.  I can see the reasoning behind it.  Since "<" shouldn't ever be in a date or url, I prefer the more aesthetically pleasing (to me) unescaped forward slashes.

But, you're right, if you change the serializer to not escape slashes, you might run into issues with other property strings that can contain a "<".

@charliedrage My personal preference for date values is ISO-8601.  It's ubiquitous, well understood, and human readable.
