### ISSUE TITLE
cpanel is broken

### ISSUE THREAD

**Issue by SoHiggo** [cloudatcost/api#18]
The cpanel seems to be broken.

I see no way to provision a new server image. Please see screenshot attached

![...](http://f.cl.ly/items/2n420N1F0T0M2K2s1I0K/2015-03-12_14-31-42.png)

**Comment by charliedrage** [comment]
Hi @SoHiggo 

That's unrelated to our API. Please open a ticket with us.

Although on a side note, disable any adblock / extensions that may be blocking certain aspects of the cpanel.
