### ISSUE TITLE
listservers cpuusage, ramusage don't seem to change

### ISSUE THREAD

**Issue by durango99** [cloudatcost/api#21]
How often does the cpuusage and ramusage json entries get polled?  I've been checking through the day and the numbers never change when I call the listservers function.

Thanks

**Comment by charliedrage** [comment]
Hi @durango99 

You're getting a little bit of information from our metric system. At the moment we're working on a metric collection service internally, however, it does not frequently update. Right now it's only refreshed upon first logging into your control panel.

**Comment by durango99** [comment]
Good to know.  Thanks for the work on the API.   Greatly appreciated.
