### ISSUE TITLE
nice API except for this...

### ISSUE THREAD

**Issue by SoHiggo** [cloudatcost/api#22]
Yeah the API is nice and all, except that I see nothing when I login?

See screenshot. Your support team is not replying to my tickets, so I am issuing tickets here.

Latest firefox, no intrusive plugins, windows.
![2015-03-21_17-23-12](https://cloud.githubusercontent.com/assets/6738367/6766051/f49ef20c-cfee-11e4-9f41-daa1a604b651.jpg)

**Comment by charliedrage** [comment]
Hi @SoHiggo 

Please stop opening new issues. See my response in the other issue.

This is unrelated to our API.

**Comment by SoHiggo** [comment]
"This is unrelated to our API. "

Except that it's not, and I want to use the API...
