### ISSUE TITLE
Decode date

### ISSUE THREAD

**Issue by andersondn** [cloudatcost/api#24]
How can I decode thist date format?

**Comment by charliedrage** [comment]
@andersondn 
Sorry for the late reply,

Which API call are you talking about?

**Comment by andersondn** [comment]
PHP

**Comment by charliedrage** [comment]
Which PHP call?

**Comment by andersondn** [comment]
I wanna make this  "time": 1425064819, looks like this: AAAA/MM/DD HH:MM:SS

**Comment by charliedrage** [comment]
Hi @andersondn 

This is in unix time. There are numerous libraries out there that you can parse this data into a user-readable date.
