### ISSUE TITLE
Rename Power Operations endpoint

### ISSUE THREAD

**Issue by drbraden** [cloudatcost/api#3]
Looks like poweropp.php has one too many "p"s in it since "Operations" has only one "p".

https://panel.cloudatcost.com/api/v1/poweropp.php
should be:
https://panel.cloudatcost.com/api/v1/powerop.php

**Comment by charliedrage** [comment]
You're right. We'll quickly make this change before many more users start using the API.

**Comment by charliedrage** [comment]
Updated API. /poweropp.php still functional however.
