### ISSUE TITLE
Python Wrapper

### ISSUE THREAD

**Issue by adc4392** [cloudatcost/api#6]
I'm not sure if this is the proper way to tell you about it, but I saw someone else opened a bug for their node.js wrapper. I still need to complete some of the documentation, but it currently has all of the base functionality that the API allows.

https://github.com/adc4392/python-cloudatcost

**Comment by charliedrage** [comment]
awesome, could I add this to the readme as a community contribution?

**Comment by adc4392** [comment]
Absolutely.

**Comment by foospidy** [comment]
@adc4392 thanks for the python wrapper. I just committed a console wrapper to your python wrapper :)  https://github.com/foospidy/CACConsole

**Comment by adc4392** [comment]
Not a problem! Glad to see it's getting use by others. I plan to get it pip-ready for easier installation as well as add some real error checking, so if you notice any bugs please submit issues.
