### ISSUE TITLE
Poweron Task Stuck in Pending

### ISSUE THREAD

**Issue by adc4392** [cloudatcost/api#7]
I committed a poweron task to one of my servers yesterday and the task still returns that it is in a pending state and the server still shows offline in the control panel.

I have not tested the other power operations at this time.

**Comment by charliedrage** [comment]
Hey,

It should be completed now. We had a bit too many requests to our API recently that we had to rate-limit. All good now.

**Comment by adc4392** [comment]
The task does seem to have cleared, and I can ping and SSH into the host, but the panel still shows it as offline (logged out and back in to be certain) and listservers.php still returns u'status': u'Powered Off' for the host.

**Comment by charliedrage** [comment]
Since we had to clear the tasks, can you perform the power-on again in the panel and/or reset? On listsevers it should update back to status: powered on

**Comment by adc4392** [comment]
I just powered the server back on via the panel and then sent a poweroff request via the API. The server is now unreachable again, but the API and panel still show it in a powered on state.

**Comment by charliedrage** [comment]
@adc4392 

Could you try again from your end? I believe I have found the bug the update not propagating to the control panel.

**Comment by adc4392** [comment]
Looks like you found it! I can power on/off via the API and both the API and the panel reflect the change properly.
